server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
zuul:
  prefix: /kun 
  ignored-services: "*"          #原真实服务名忽略 microservicecloud-dept 使用 * 忽略所有的真实服务名
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/** 
info:
  app.name: kun-microcloud
  company.name: www.yangkun315.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$